language: ruby

rvm:
  - 3.0
  - 2.7
  - 2.6
  - 2.5
  - jruby
  - truffleruby

matrix:
  allow_failures:
    - rvm: jruby
    - rvm: truffleruby
  fast_finish: true

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'

bundler_args: --jobs 4 --retry 4

before_script:

# execute rspec tests, rubocop and bundle:audit
script:
  bundle exec rake ci
