language: ruby

rvm:
  - ruby-head
  - 2.6
  - 2.5
  - 2.4
  - jruby
  - truffleruby

matrix:
  allow_failures:
    - rvm: jruby
    - rvm: truffleruby
  fast_finish: true

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'

bundler_args: --jobs 3 --retry 3

before_script:

# execute rspec tests, rubocop and bundle:audit
script:
  bundle exec rake
